# Fish completion for boxr
complete -c boxr -f
complete -c boxr -n "__fish_use_subcommand" -a run -d 'Run a container'
complete -c boxr -n "__fish_use_subcommand" -a pull -d 'Pull an image'
complete -c boxr -n "__fish_use_subcommand" -a stop -d 'Stop a container'
complete -c boxr -n "__fish_use_subcommand" -a start -d 'Start a container'
complete -c boxr -n "__fish_use_subcommand" -a logs -d 'Fetch logs'
complete -c boxr -n "__fish_use_subcommand" -a exec -d 'Execute in container'
complete -c boxr -n "__fish_use_subcommand" -a inspect -d 'Inspect objects'
complete -c boxr -n "__fish_use_subcommand" -a build -d 'Build image from Dockerfile'
complete -c boxr -n "__fish_use_subcommand" -a compose -d 'Compose multi-container app'
complete -c boxr -n "__fish_use_subcommand" -a volume -d 'Manage volumes'
complete -c boxr -n "__fish_use_subcommand" -a network -d 'Manage networks'
complete -c boxr -n "__fish_use_subcommand" -a daemon -d 'Start daemon'
complete -c boxr -n "__fish_use_subcommand" -a stats -d 'Live container stats'
complete -c boxr -n "__fish_use_subcommand" -a events -d 'Stream container events'
complete -c boxr -n "__fish_use_subcommand" -a save -d 'Save image tar'
complete -c boxr -n "__fish_use_subcommand" -a load -d 'Load image tar'
complete -c boxr -n "__fish_use_subcommand" -a login -d 'Login to registry'
complete -c boxr -n "__fish_use_subcommand" -a logout -d 'Logout from registry'
complete -c boxr -n "__fish_use_subcommand" -a images -d 'List images'
complete -c boxr -n "__fish_use_subcommand" -a ps -d 'List containers'
complete -c boxr -n "__fish_use_subcommand" -a rm -d 'Remove containers'
complete -c boxr -n "__fish_use_subcommand" -a rmi -d 'Remove images'
complete -c boxr -n "__fish_use_subcommand" -a spec -d 'Generate OCI spec'
complete -c boxr -n "__fish_use_subcommand" -a completion -d 'Generate shell completions'
complete -c boxr -n "__fish_use_subcommand" -a alias -d 'Docker drop-in alias'

